spring.application.name=BMS
spring.datasource.url=jdbc:mysql://mysql-1ee31d88-bmsadmin.d.aivencloud.com:19727/bms?sslMode=REQUIRED
spring.datasource.username=avnadmin

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false